version: '3.8'

services:
  web:
    image: php:7.4-fpm
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel-net
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DATABASE_URL=pgsql://alumni_macl_user:5J4tVgixswjRYgr1BFEiQf2MXnE6xwNP@db/alumni_macl
      - APP_KEY=base64:OyACJZzMH4g37NRVjeWACaXjOTeXj5VZvPZpTrH5hWs=
      # Add other Laravel-specific environment variables as needed

  db:
    image: postgres:13
    container_name: laravel-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alumni_macl_user
      - POSTGRES_PASSWORD=5J4tVgixswjRYgr1BFEiQf2MXnE6xwNP
      - POSTGRES_DB=alumni_macl

networks:
  laravel-net:
    driver: bridge
